// Environment configuration generated by Netlify build script
window.NETLIFY_ENV = {
    RAPIDAPI_KEY: '2e08ed83camsh44dc27a6c439f8dp1c388ajsn65cd74585fef',
    BUILD_TIME: '2025-01-27T12:00:00.000Z'
};

console.log('🔧 Netlify environment configuration loaded');
console.log('🔑 API Key available:', !!window.NETLIFY_ENV.RAPIDAPI_KEY);
