#!/usr/bin/env node

// Netlify Build Script
// This script creates a simple environment configuration for the client-side
// Run during Netlify build process

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

console.log('🔧 Starting Netlify build script...');

// Get current directory for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Main build process
async function main() {
    try {
        // Get environment variables
        const rapidApiKey = process.env.VITE_RAPIDAPI_KEY || process.env.RAPIDAPI_KEY;
        
        console.log('🔑 RapidAPI Key found:', !!rapidApiKey);

        // Create a simple environment configuration file
        const envConfig = `// Environment configuration generated by Netlify build script
window.NETLIFY_ENV = {
    RAPIDAPI_KEY: '${rapidApiKey || ''}',
    BUILD_TIME: '${new Date().toISOString()}'
};

console.log('🔧 Netlify environment configuration loaded');
console.log('🔑 API Key available:', !!window.NETLIFY_ENV.RAPIDAPI_KEY);
`;

        // Write the environment configuration
        const envConfigPath = path.join(__dirname, '..', 'config', 'netlify-env.js');
        fs.writeFileSync(envConfigPath, envConfig);
        console.log(`✅ Environment configuration written to ${envConfigPath}`);

        console.log('✅ Netlify build script completed successfully');

    } catch (error) {
        console.error('❌ Error in Netlify build script:', error);
        process.exit(1);
    }
}

// Run the build script
main();
